name: CD

on: 
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3

      - name: Install NodeJS
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14

      - name: Pull dependencies
        run: npm i

      - name: Update Project files
        run: npm run pull-external-data

      - name: Push changes
        uses: EndBug/add-and-commit@v7
        with:
          default_author: 'github_actions'
          branch: master
          add: 'data/projects'
          message: '[Chore] Update project files'
          push: true